version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - pong_db
    networks:
      - total_network
    env_file:
      - ./backend/.env
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3001:3001"
    env_file:
      - ./frontend/.env
  pong_db:
    container_name: pong_db
    image: postgres
    environment:
      POSTGRE_USER : postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pongserv
    ports:
      - "5432:5432"
    networks:
      - total_network
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

networks:
  total_network:
    driver: bridge
