name: Deploy to AWS EC2

on:
  push:
    branches:
      - FIX-Github-action-login-failed-problem

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies and build backend
      run: |
        cd backend
        npm ci --production
        npm run build

    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm ci --production
        npm run build

    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        # port: ${{ secrets.PORT }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "backend/dist"
        target: /home/ubuntu/pongserv/backend
    
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        # port: ${{ secrets.PORT }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        source: "frontend/build"
        target: /home/ubuntu/pongserv/frontend
  
    # - name: Deploy to AWS EC2
    #   env:
    #     PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    #     HOST: ${{ secrets.EC2_HOST }}
    #     USER: ${{ secrets.EC2_USER }}
    #   run: |
    #     echo "$PRIVATE_KEY" > private_key.pem
    #     chmod 600 private_key.pem
    #     echo "Fetching remote SSH server public key"
    #     ssh-keyscan $HOST >> ~/.ssh/known_hosts
    #     scp -i private_key.pem -o BatchMode=yes -o StrictHostKeyChecking=yes -r backend/dist $USER@$HOST:/home/$HOST/pongserv/backend
    #     scp -i private_key.pem -o BatchMode=yes -o StrictHostKeyChecking=yes -r frontend/build $USER@$HOST:/home/$HOST/pongserv/frontend
    #     ssh -i private_key.pem -o BatchMode=yes -o StrictHostKeyChecking=yes $USER@$HOST "pm2 restart backend && pm2 restart frontend"
    #     rm -f private_key.pem
